# Generated by Django 4.2.2 on 2023-10-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_employee_position_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non-IT')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
